import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { cn } from '@/utils/classNames';
import './globals.css';

const roboto = Roboto({
	variable: '--font-primary',
	subsets: ['latin'],
	weight: ['400', '500', '700', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn(roboto.variable, 'container')}>{children}</body>
		</html>
	);
}
